markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: D++
host: agathewiky.github.io
desc: 站在巨人的肩膀上.

custom:
    category:
        default: default
        another: mistake
    categories:
      - name:  default
        title: 随笔

      - name:  mistake
        title: 折戟沉沙

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: wiky
        email: zetao.wei@gmail.com
        disqus: agathewiky                          # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: agathewiky                          # GitHub账号

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
