markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Wiky
host: agathewiky.github.io
desc: Some description of your site.

custom:
    category:
        default: Default
        another: Another
    categories:
      - name:  default
        title: Default

      - name:  another
        title: Another

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: wiky
        email: we.agathe@gmail.com
        disqus: agathewiky                             # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: agathewiky                          # GitHub账号
        gravatar: 34048bba022a44ff87af3970ee404710  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
